/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcRyeHarvestLossInputs {
    'socket': string;
  }
  interface AgcRyeHarvestLossInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcRyeHarvestLossProgress {
    'socket': string;
  }
  interface AgcRyeHarvestLossProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcRyeHarvestLossResultsPlaceholder {}
  interface AgcRyeHarvestLossResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcRyeHarvestLossResults {
    'socket': string;
  }
  interface AgcRyeHarvestLossResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcRyeHarvestLoss {
    'mode': 'full' | 'step';
    'socket': string;
    'tract': string;
    'units': any;
  }
  interface AgcRyeHarvestLossAttributes extends StencilHTMLAttributes {
    'mode'?: 'full' | 'step';
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
    'units'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcRyeHarvestLossInputs': Components.AgcRyeHarvestLossInputs;
    'AgcRyeHarvestLossProgress': Components.AgcRyeHarvestLossProgress;
    'AgcRyeHarvestLossResultsPlaceholder': Components.AgcRyeHarvestLossResultsPlaceholder;
    'AgcRyeHarvestLossResults': Components.AgcRyeHarvestLossResults;
    'AgcRyeHarvestLoss': Components.AgcRyeHarvestLoss;
  }

  interface StencilIntrinsicElements {
    'agc-rye-harvest-loss-inputs': Components.AgcRyeHarvestLossInputsAttributes;
    'agc-rye-harvest-loss-progress': Components.AgcRyeHarvestLossProgressAttributes;
    'agc-rye-harvest-loss-results-placeholder': Components.AgcRyeHarvestLossResultsPlaceholderAttributes;
    'agc-rye-harvest-loss-results': Components.AgcRyeHarvestLossResultsAttributes;
    'agc-rye-harvest-loss': Components.AgcRyeHarvestLossAttributes;
  }


  interface HTMLAgcRyeHarvestLossInputsElement extends Components.AgcRyeHarvestLossInputs, HTMLStencilElement {}
  var HTMLAgcRyeHarvestLossInputsElement: {
    prototype: HTMLAgcRyeHarvestLossInputsElement;
    new (): HTMLAgcRyeHarvestLossInputsElement;
  };

  interface HTMLAgcRyeHarvestLossProgressElement extends Components.AgcRyeHarvestLossProgress, HTMLStencilElement {}
  var HTMLAgcRyeHarvestLossProgressElement: {
    prototype: HTMLAgcRyeHarvestLossProgressElement;
    new (): HTMLAgcRyeHarvestLossProgressElement;
  };

  interface HTMLAgcRyeHarvestLossResultsPlaceholderElement extends Components.AgcRyeHarvestLossResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcRyeHarvestLossResultsPlaceholderElement: {
    prototype: HTMLAgcRyeHarvestLossResultsPlaceholderElement;
    new (): HTMLAgcRyeHarvestLossResultsPlaceholderElement;
  };

  interface HTMLAgcRyeHarvestLossResultsElement extends Components.AgcRyeHarvestLossResults, HTMLStencilElement {}
  var HTMLAgcRyeHarvestLossResultsElement: {
    prototype: HTMLAgcRyeHarvestLossResultsElement;
    new (): HTMLAgcRyeHarvestLossResultsElement;
  };

  interface HTMLAgcRyeHarvestLossElement extends Components.AgcRyeHarvestLoss, HTMLStencilElement {}
  var HTMLAgcRyeHarvestLossElement: {
    prototype: HTMLAgcRyeHarvestLossElement;
    new (): HTMLAgcRyeHarvestLossElement;
  };

  interface HTMLElementTagNameMap {
    'agc-rye-harvest-loss-inputs': HTMLAgcRyeHarvestLossInputsElement
    'agc-rye-harvest-loss-progress': HTMLAgcRyeHarvestLossProgressElement
    'agc-rye-harvest-loss-results-placeholder': HTMLAgcRyeHarvestLossResultsPlaceholderElement
    'agc-rye-harvest-loss-results': HTMLAgcRyeHarvestLossResultsElement
    'agc-rye-harvest-loss': HTMLAgcRyeHarvestLossElement
  }

  interface ElementTagNameMap {
    'agc-rye-harvest-loss-inputs': HTMLAgcRyeHarvestLossInputsElement;
    'agc-rye-harvest-loss-progress': HTMLAgcRyeHarvestLossProgressElement;
    'agc-rye-harvest-loss-results-placeholder': HTMLAgcRyeHarvestLossResultsPlaceholderElement;
    'agc-rye-harvest-loss-results': HTMLAgcRyeHarvestLossResultsElement;
    'agc-rye-harvest-loss': HTMLAgcRyeHarvestLossElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
